#proxy_url: "http://192.168.215.30:3128"
#no_proxy_list: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
proxy_url: "http://192.168.215.30:3128"
no_proxy_list: "127.0.0.1,localhost,192.168.215.0/24,10.42.0.0/16,10.43.0.0/16,.svc,.cluster.local"
