---
# === 1. Désactiver le pare-feu firewalld ===
- name: Désactiver firewalld (pare-feu par défaut sur Red Hat)
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

# === Désactiver SELinux (nécessaire pour Cilium / eBPF) ===

- name: Mettre SELinux en permissive immédiatement
  command: setenforce 0
  ignore_errors: true

- name: Désactiver SELinux définitivement
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    replace: 'SELINUX=disabled'
  ignore_errors: true

# === 2. Installer les dépendances nécessaires  ===
- name: Installer les dépendances nécessaires
  yum:
    name:
      - curl
      - tar
      - socat
      - conntrack-tools
      - iptables
      - ca-certificates
      - nfs-utils
    state: present

# === 3. Désactiver le swap (nécessaire pour Kubernetes) ===
- name: Désactiver le swap immédiatement
  command: swapoff -a
  ignore_errors: true

- name: Désactiver le swap au redémarrage
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '# \1'
  ignore_errors: true

# === 4. Charger les modules kernel requis ===
- name: Charger les modules kernel requis
  command: modprobe {{ item }}
  loop:
    - br_netfilter
    - overlay
  ignore_errors: true

- name: Persister les modules kernel
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
    mode: '0644'

- name: Appliquer la configuration sysctl Kubernetes
  copy:
    dest: /etc/sysctl.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv4.conf.all.send_redirects=0
      net.ipv4.conf.default.send_redirects=0
      net.ipv4.conf.default.accept_source_route=0
      net.ipv4.conf.all.accept_redirects=0
      net.ipv4.conf.default.accept_redirects=0
      net.ipv4.conf.all.log_martians=1
      net.ipv4.conf.default.log_martians=1
      net.ipv4.conf.all.rp_filter=1
      net.ipv4.conf.default.rp_filter=1
      net.ipv6.conf.all.accept_ra=0
      net.ipv6.conf.default.accept_ra=0
      net.ipv6.conf.all.accept_redirects=0
      net.ipv6.conf.default.accept_redirects=0
      kernel.keys.root_maxbytes=25000000
      kernel.keys.root_maxkeys=1000000
      kernel.panic=10
      kernel.panic_on_oops=1
      vm.overcommit_memory=1
      vm.panic_on_oom=0
      net.ipv4.ip_local_reserved_ports=30000-32767
      net.bridge.bridge-nf-call-iptables=1
      net.bridge.bridge-nf-call-arptables=1
      net.bridge.bridge-nf-call-ip6tables=1
    mode: '0644'

- name: Recharger sysctl
  command: sysctl --system


# === 6. Nettoyage ===
- name: Nettoyer les paquets inutiles
  yum:
    autoremove: yes
